### ISSUE TITLE
Cluster ElasticSearch dynamic

### ISSUE THREAD

**Issue by jeromecamilleri** [github/elasticsearch-srv-discovery#2]
Hi,

I try to use elasticsearch-srv-discovery plugin's into an ES cluster.
For 2 initial nodes cluster is ok and TCP discovery work well with DNS request answer by consul.
But when I scale up my cluster and try to create a new ElasticSearch instance on the same network with the same parameter and with consult's service update, my new ES's node don"t connect to the cluster and work alone...
I notice also that when I try to initiate my cluster with 3 nodes, I have only a cluster of two nodes with one alone...

Thanks for your tips...

Jérôme

**Comment by JigarJoshi** [comment]
Could you turn on TRACE logging for discovery module and paste some more information here, With provided information I am not sure what could be the problem here, but I forked this plugin and made it consul specific, if you want to give it a try https://github.com/lithiumtech/elasticsearch-consul-discovery

**Comment by grantr** [comment]
@jeromecamilleri I'm surprised TCP discovery works for you at all, since it doesn't for me. I haven't had time to debug it yet.

**Comment by jeromecamilleri** [comment]
Thanks JigarJoshi, forks version of your plugin using conul API work well in my environment.

**Comment by JigarJoshi** [comment]
:+1:

**Comment by chrismwendt** [comment]
@jeromecamilleri: [Version 1.5.0](https://github.com/github/elasticsearch-srv-discovery/releases/tag/1.5.0) was just released :tada: and should work for you. Give it a try and reopen this issue if it doesn't.
